### PR TITLE
Add wget

### PR DESCRIPTION
**Pull request by Yi-Tseng**

### CODE REVIEW

**Comment by John-Lin** [comment]
Do we need  `wget` for installing  Ryu ?

**Comment by pichuang** [comment]
It's depend on [ryuInstallHelper.sh#L26](https://github.com/sdnds-tw/ryuInstallHelper/blob/master/ryuInstallHelper.sh#L26) Right? @TakeshiTseng

**Comment by John-Lin** [comment]
@pichuang I missed it. Thanks for pointing it out. :+1: 
@TakeshiTseng Thanks

**Comment by TakeshiTseng** [comment]
:+1:

**Pull request merged**
